### ISSUE TITLE
packagist version wrong

### ISSUE THREAD

**Issue by ziegi** [llaville/umlwriter#6] opened 2018-03-13 18:13 UTC
While a direct download http://bartlett.laurent-laville.org/get/umlwriter-1.2.0.phar gives me umlwriter in the Version 1.2.0,
a download using compser with version string "^1.2.0" oder "dev-master" always gives me umlwriter in the Version 1.0

**Comment by llaville** [comment] 2018-03-13 19:10
Hello,
I cannot reproduced this issue. 
With `Composer version 1.6.3 2018-01-31 16:28:17` and `PHP 7.1.15`, package `bartlett/umlwriter` 1.2.0 was successfully downloaded from packagist.

Please provide how did you tried, command syntax, and plateform version with software versions used !

**Comment by ziegi** [comment] 2018-03-13 19:28
Composer version 1.5.1 2017-08-09 16:07:22
PHP 7.1.15-1+ubuntu17.10.1+deb.sury.org+2

steps to reproduce:
1. create empty dir and cd into it
2. create very basic composer.json file containing:
{
    "require-dev": {
       "bartlett/umlwriter": "dev-master"
    }
}
3. run composer update
4. run vendor/bin/umlwriter -V
result: umlWriter version 1.0-g1a302bf

Same steps as above but with different version strings:
"bartlett/umlwriter": "^1.2" -> umlWriter version 1.0-1.2.0
"bartlett/umlwriter": "^1.2.0" -> umlWriter version 1.0-1.2.0
Sorry, i am very sure that two hours ago this gave me a umlWriter version 1.0


while the direct download of http://bartlett.laurent-laville.org/get/umlwriter-1.2.0.phar
php ../addons/umlwriter-1.2.0.phar -V -> umlWriter version 1.2.0

**Comment by llaville** [comment] 2018-03-13 19:55
I've just download composer version 1.5.1, and cannot reproduced issue.

I suggest to run composer command with verbose level 3 (-vvv) and analyse actions

**Comment by ziegi** [comment] 2018-03-14 09:37
I am not familiar with debugging composer, 
so here is the output, maybe you can understand it:

I am starting out with a cleared composer cache:
```
rm -rf vendor/
rm -rf composer.lock 
rm -rf ~/.cache/composer/
```
composer.json:
```
{
    "require-dev": {
       "bartlett/umlwriter": "^1.2.0"
    }
}
```
 composer update -vvv
```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/ziegi/test): git branch --no-color --no-abbrev -v
Executing command (/home/ziegi/test): git describe --exact-match --tags
Executing command (/home/ziegi/test): git log --pretty="%H" -n1 HEAD
Executing command (/home/ziegi/test): hg branch
Executing command (/home/ziegi/test): fossil branch list
Executing command (/home/ziegi/test): fossil tag list
Executing command (/home/ziegi/test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /home/ziegi/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.5.1 (2017-08-09 16:07:22) with PHP 7.1.15-1+ubuntu17.10.1+deb.sury.org+2 on Linux / 4.9.86-040986-lowlatency
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Downloading http://packagist.org/p/provider-2013%24efcbaad82b5907329b313861b92aa252c6e6bf8c0d57e1677e8c541428d0ece4.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2013.json into cache
Downloading http://packagist.org/p/provider-2014%243e1db169512fb519275c80912500fc04b5a438413c65039bb16db3b87658e2ec.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2014.json into cache
Downloading http://packagist.org/p/provider-2015%24b96253486ae8dfebcb021a72f76a0088ebc72a30b374b9444eb24e5ce5449bfa.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2015.json into cache
Downloading http://packagist.org/p/provider-2016%24c9ef85276b109d69463790290dcc1cd04a6080ac60edc79a1a63cb0148ea9093.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2016.json into cache
Downloading http://packagist.org/p/provider-2017%24f8a2f614a64545740ea3da0331c3d7e8059f999a1e61069236d0020366a06f00.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2017.json into cache
Downloading http://packagist.org/p/provider-2017-04%24c371495babeed642b003c3480b97887f3aaa0ba0c23abe9ac4f4f95c64f40ed8.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2017-04.json into cache
Downloading http://packagist.org/p/provider-2017-07%244cc6d86d2edcbe27c6d95212cb139d81f4a229467d365f71bca3c5ac1bc9cf96.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2017-07.json into cache
Downloading http://packagist.org/p/provider-2017-10%2468772ceb40521770a665655453a2e22d838b1dc57ebc7410fba8042caec7093e.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2017-10.json into cache
Downloading http://packagist.org/p/provider-2018-01%24867df6eb3e4c6ed0af4ff853275286b4989017105b783ee560152dac6e672e04.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-2018-01.json into cache
Downloading http://packagist.org/p/provider-archived%247c82e16a0cd3559e8e546c295851ee4f9b915300c1457e0d45d84b05feaa8f5e.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-archived.json into cache
Downloading http://packagist.org/p/provider-latest%2477d5181db158313c72a6a40b91f106d09e8e60f3454ab409f424c1ff8af184fe.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/p-provider-latest.json into cache
Downloading http://packagist.org/p/bartlett/umlwriter%244abf82a3a91ee85a23ea5832d6b43d99d3757b07ff2551a9ef7aa1ea91a1aadb.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-bartlett$umlwriter.json into cache
Downloading http://packagist.org/p/symfony/console%24791e4dad0a77ae80f3772198c3dd055ed3719f6f60a6a21fefcaf9b2873a1fa0.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-symfony$console.json into cache
Downloading http://packagist.org/p/sebastian/version%246bcd972dbe9b9b56b7547a9b66813fa43c876aa2ff324fa7bce136dedcc135cc.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-sebastian$version.json into cache
Downloading http://packagist.org/p/symfony/debug%24634d83e62999f465165c8ec1b151b649b4b72e78d26ea0153e822281c5259d58.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-symfony$debug.json into cache
Downloading http://packagist.org/p/symfony/polyfill-mbstring%2478a6d4f3fe4ef2206b10b0130b29563fb755941e32921c37015622f9b7484f61.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-mbstring.json into cache
Downloading http://packagist.org/p/psr/log%24506defe098874e07a7b888e49ff0f6dd45054d013ec99d279e5e41bfe75c294d.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-psr$log.json into cache
Downloading http://packagist.org/p/symfony/dependency-injection%246d261dcc69f587bf7f2ac0e97afdea3d8a31a63ab3682621ecf63fa8c729430b.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-symfony$dependency-injection.json into cache
Downloading http://packagist.org/p/symfony/process%24c51f2d0ea98b15489c6469811bf7f88416f8e388b7b62d7351fbee284f798ae7.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-symfony$process.json into cache
Downloading http://packagist.org/p/symfony/http-kernel%24163f6bb038b0f541bd766f489335185f3c83f4056220c0c28da22b6cd3b3094b.json
Writing /home/ziegi/.cache/composer/repo/https---packagist.org/provider-symfony$http-kernel.json into cache
Resolving dependencies through SAT
Dependency resolution completed in 0.024 seconds
Analyzed 1709 packages to resolve dependencies
Analyzed 25439 rules to resolve dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.000 seconds
Package operations: 6 installs, 0 updates, 0 removals
Installs: sebastian/version:2.0.1, psr/log:1.0.2, symfony/debug:v4.0.6, symfony/polyfill-mbstring:v1.7.0, symfony/console:v3.4.6, bartlett/umlwriter:1.2.0
  - Installing sebastian/version (2.0.1): Downloading https://api.github.com/repos/sebastianbergmann/version/zipball/99732be0ddb3361e16ad77b68ba41efc8e979019
Downloading (100%)Writing /home/ziegi/.cache/composer/files/sebastian/version/c315a200d32565a6d8ebb3495cb5ae34c5ced3c8.zip into cache from /home/ziegi/test/vendor/sebastian/version/1dbe54ca08a5ff44197316096a2f7583

 Extracting archiveExecuting command (CWD): unzip -qq  '/home/ziegi/test/vendor/sebastian/version/1dbe54ca08a5ff44197316096a2f7583' -d '/home/ziegi/test/vendor/composer/fb61d3e3'
    REASON: bartlett/umlwriter 1.2.0 requires sebastian/version ~1.0|~2.0 -> satisfiable by sebastian/version[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1].

  - Installing psr/log (1.0.2): Downloading https://api.github.com/repos/php-fig/log/zipball/4ebe3a8bf773a19edfe0a84b6585ba3d401b724d
Downloading (100%)Writing /home/ziegi/.cache/composer/files/psr/log/216fe71da49480fa51edd2c2fe0f7f93d5e2714a.zip into cache from /home/ziegi/test/vendor/psr/log/bcea54e320a64a2bbac75b6ea2ad936c

 Extracting archiveExecuting command (CWD): unzip -qq  '/home/ziegi/test/vendor/psr/log/bcea54e320a64a2bbac75b6ea2ad936c' -d '/home/ziegi/test/vendor/composer/eeab8678'
    REASON: symfony/debug v4.0.6 requires psr/log ~1.0 -> satisfiable by psr/log[1.0.0, 1.0.1, 1.0.2].

  - Installing symfony/debug (v4.0.6): Downloading https://api.github.com/repos/symfony/debug/zipball/1721e4e7effb23480966690cdcdc7d2a4152d489
Downloading (100%)Writing /home/ziegi/.cache/composer/files/symfony/debug/dabe2cad5965bc37338ff834a3cb0aebb9e1d18b.zip into cache from /home/ziegi/test/vendor/symfony/debug/5446ce1c38f33c0ebde7147f6a5b342a

 Extracting archiveExecuting command (CWD): unzip -qq  '/home/ziegi/test/vendor/symfony/debug/5446ce1c38f33c0ebde7147f6a5b342a' -d '/home/ziegi/test/vendor/composer/b689db3d'
    REASON: symfony/console v3.4.6 requires symfony/debug ~2.8|~3.0|~4.0 -> satisfiable by symfony/debug[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6].

  - Installing symfony/polyfill-mbstring (v1.7.0): Downloading https://api.github.com/repos/symfony/polyfill-mbstring/zipball/78be803ce01e55d3491c1397cf1c64beb9c1b63b
Downloading (100%)Writing /home/ziegi/.cache/composer/files/symfony/polyfill-mbstring/fba0e1e5bbbe86cce4b329f9c3c55f8a9d7d8097.zip into cache from /home/ziegi/test/vendor/symfony/polyfill-mbstring/546917b65cafcc50a10553f139798111

 Extracting archiveExecuting command (CWD): unzip -qq  '/home/ziegi/test/vendor/symfony/polyfill-mbstring/546917b65cafcc50a10553f139798111' -d '/home/ziegi/test/vendor/composer/b66ddf8d'
    REASON: symfony/console v3.4.6 requires symfony/polyfill-mbstring ~1.0 -> satisfiable by symfony/polyfill-mbstring[v1.0.0, v1.0.1, v1.1.0, v1.1.1, v1.2.0, v1.3.0, v1.3.1, v1.4.0, v1.5.0, v1.6.0, v1.7.0].

  - Installing symfony/console (v3.4.6): Downloading https://api.github.com/repos/symfony/console/zipball/067339e9b8ec30d5f19f5950208893ff026b94f7
Downloading (100%)Writing /home/ziegi/.cache/composer/files/symfony/console/4df8b259ecde284d3b93d723a20ef5b2ca2bfb03.zip into cache from /home/ziegi/test/vendor/symfony/console/161153c5f2f75e837caa390034f9cd10

 Extracting archiveExecuting command (CWD): unzip -qq  '/home/ziegi/test/vendor/symfony/console/161153c5f2f75e837caa390034f9cd10' -d '/home/ziegi/test/vendor/composer/20dbfade'
    REASON: bartlett/umlwriter 1.2.0 requires symfony/console ~2.5|~3.0 -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6].

  - Installing bartlett/umlwriter (1.2.0): Downloading https://api.github.com/repos/llaville/umlwriter/zipball/e4a204db7416ce49712978287f6c631b54c09008
Downloading (100%)Writing /home/ziegi/.cache/composer/files/bartlett/umlwriter/03fe1c76b7b5842a262de396615c7aafd7af5b3c.zip into cache from /home/ziegi/test/vendor/bartlett/umlwriter/8fa1e39c15d27a224934e2c76aef28f4

 Extracting archiveExecuting command (CWD): unzip -qq  '/home/ziegi/test/vendor/bartlett/umlwriter/8fa1e39c15d27a224934e2c76aef28f4' -d '/home/ziegi/test/vendor/composer/12c7d977'
    REASON: Required by the root package: Install command rule (install bartlett/umlwriter 1.2.0)

symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/lock ()
symfony/console suggests installing symfony/process ()
bartlett/umlwriter suggests installing bartlett/php-reflect (Reverse-engine, default solution)
bartlett/umlwriter suggests installing andrewsville/php-token-reflection (Reverse-engine, alternative solution)
Reading /home/ziegi/test/vendor/composer/installed.json
Writing lock file
Generating autoload files
```
vendor/bin/umlwriter -V
`umlWriter version 1.0-dev
`

**Comment by llaville** [comment] 2018-03-17 08:46
version displayed by `umlWriter` command was wrong: see commit [cb7dbdc](https://github.com/llaville/umlwriter/commit/cb7dbdc23b46eda838fdc03b15313fdd78e1719f)

**Comment by llaville** [comment] 2018-03-17 10:16
For reason given in my previous comment, I think this issue is fixed !

If you are agree, you can close this report.

**Comment by ziegi** [comment] 2018-03-17 13:56
Yes, i can confirm that the version printed now is the correct one.
Thanks for fixing.

**Closed** 2018-03-17 13:56 UTC
